source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2', group: 'development'
gem 'debugger', group: 'development'
gem 'quiet_assets', group: 'development'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
gem 'spree', :path => '..'
gem 'spree_auth_devise', :github => 'spree/spree_auth_devise'
gem 'spree_paypal_express', :git => 'git://github.com/spree/spree_paypal_express.git'
gem 'spree_invoice', :path => '../../spree_invoice_generator'

#https://github.com/damianogiacomello/spree_invoice_generator (Integrated from)
gem 'wicked_pdf' , '0.9.6'
group :test,:development do
	gem "rspec-rails", "2.11.0"
  gem 'capybara', '1.1.2'
  gem 'shoulda-matchers'
  gem 'cucumber-rails', :require => false
  gem 'guard-rspec', '1.2.1'
  gem 'guard-spork', :github => 'guard/guard-spork'
  gem 'spork', '0.9.2'
  gem 'factory_girl_rails', '~> 3.5.0'
end

group :test do
  gem 'capybara', '1.1.2'
  gem 'rb-inotify', '~> 0.9'
  gem 'libnotify', '0.5.9'
end

group :development do
  gem 'webrick' #, '~> 1.3.1'
end